many incremental improvements
* bunch of new vim plugins
* venv convenience functions expanded and improved
* logging convenience functions
* new git aliases
* vim jinja syntax fix

diff --git a/bashrc.d/function b/bashrc.d/function
--- a/bashrc.d/function
+++ b/bashrc.d/function
@@ -97,15 +97,84 @@ function vimrc() {
   vim ~/.vimrc "${OPTS[@]}"
 }
 
-# quickly access git help
+# quickly access vim help
 function :help() {
-  vim "+help $1" "+2close"
+  vim "+help $1" "+silent only"
+}
+
+function _condition_venv() {
+  for venv in venv .venv ; do
+    local prg="${venv}/bin/${1}"
+    if [[ -e "$prg" ]] ; then
+      echo "$prg"
+      return 0
+    fi
+  done
+  echo >&2 venv "$1" not found
+  return 1
 }
 
 function py() {
-  if [[ -x venv/bin/python ]] ; then venv/bin/python "$@" ; else  python "$@" ; fi
+  prg="$(_condition_venv python)" && "$prg" "$@"
 }
 
 function pi() {
-  if [[ -x venv/bin/pip ]] ; then venv/bin/pip "$@" ; else  pip "$@" ; fi
+  prg="$(_condition_venv pip)" && "$prg" "$@"
+}
+
+function loggit() {
+  if [[ -n "$(set +o | fgrep 'set +o pipefail')" ]] ; then
+    function loggit__exit() {
+      trap - RETURN
+      unset -f loggit__exit
+      set +o pipefail
+    }
+    trap loggit__exit RETURN
+    set -o pipefail
+  fi
+  name="$1"
+  shift
+  "$@" 2>&1 | tee /tmp/log-"${name}-$(gdate --iso=seconds | sed 's/-[^-]*$//;y/T:/_-/').log"
+}
+
+function logname() {
+  local prefix=
+  local num=
+  while [[ -n "$1" ]] ; do
+    local arg="$1"
+    if [[ "$arg" =~ ^[1-9][0-9]*$ ]] ; then
+      if [[ -z "$num" ]] ; then
+        num="$arg"
+      else
+        echo "two numbers provided" >&2
+        return 1
+      fi
+    elif [[ -z "$prefix" && -n "$arg" ]] ; then
+      prefix="$arg"
+    else
+      echo "bad input" >&2
+      return 1
+    fi
+    shift
+  done
+  if [[ -z "$num" ]] ; then
+    num=1
+  fi
+  local pattern=/tmp/log
+  if [[ -n "$prefix" ]] ; then
+    pattern="${pattern}-${prefix}"
+  fi
+  ls -t "${pattern}"-* | sed -n "${num}p"
+}
+function lesslog() {
+  local lname="$(logname "$@")"
+  local rv="$?"
+  if [[ "$rv" != 0 ]] ; then
+    return "$rv"
+  fi
+  less "$lname"
+}
+
+function activate() {
+  prg="$(_condition_venv activate)" && source "$prg"
 }
